# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_bill_date'),
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgets.Category')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='billcategory',
            unique_together=set([('bill', 'category')]),
        ),
    ]
