# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-07 08:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0002_auto_20180325_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Bought item name')),
                ('quantity', models.IntegerField(default=1)),
                ('amount', models.FloatField(verbose_name='Price of one item')),
                ('date', models.DateField(verbose_name='Date of the spending')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Speding was logged')),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.Bill')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='spending',
            unique_together=set([('name', 'bill')]),
        ),
    ]
