# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 11:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spendings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spending',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spending',
            name='amount',
            field=models.FloatField(verbose_name='Total amount of all items in this spendings'),
        ),
    ]
