# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 12:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0002_auto_20180410_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spending',
            name='user',
        ),
    ]
