# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spendings', '0003_remove_spending_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spending',
            name='bill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spendings', to='bills.Bill'),
        ),
    ]
