version: '2'

# for local environment only
services:
  db:
    environment:
      POSTGRES_DB: local-db
      POSTGRES_USER: local-user
      POSTGRES_PASSWORD: local-password
    restart: always
    image: postgres:9.5
    expose:
      - "5432"

  app:
    environment:
      DATABASE_URL: postgres://local-user:local-password@db/local-db
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
    ports:
      - "8001:8000"
    depends_on:
      - db
