# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('sha256_hash_hex', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('parced_data', models.TextField()),
            ],
        ),
    ]
