# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-25 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bill',
            old_name='parced_data',
            new_name='parsed_data',
        ),
    ]
