# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0003_bill_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
