# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20180615_1241'),
        ('bills', '0004_bill_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='categories',
            field=models.ManyToManyField(through='budgets.BillCategory', to='budgets.Category'),
        ),
    ]
